//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGallery
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_left_disabled = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_left_enabled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrow_right_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arrow_right_enabled = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int image_border = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int natureimage1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int natureimage10 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int natureimage11 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int natureimage12 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int natureimage13 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int natureimage14 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int natureimage15 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int natureimage2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int natureimage3 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int natureimage4 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int natureimage5 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int natureimage6 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int natureimage7 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int natureimage8 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int natureimage9 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int selected_image_border = 2130837526;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int gallery = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int gallery_relative_layout = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int left_arrow_imageview = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int right_arrow_imageview = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int selected_imageview = 2131034112;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
