//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMovies
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bgh = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int delete = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int errorbg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int find = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int genre = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int gradient_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int gradient_bg_hover = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_menu_search = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int list_selector = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int save = 2130837517;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050025
			public const int cbGenre = 2131034149;
			
			// aapt resource value: 0x7f050019
			public const int genre = 2131034137;
			
			// aapt resource value: 0x7f050008
			public const int imgAdd = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int imgAddGenre = 2131034131;
			
			// aapt resource value: 0x7f05000b
			public const int imgBack = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int imgDelete = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int imgEdit = 2131034121;
			
			// aapt resource value: 0x7f050012
			public const int imgFind = 2131034130;
			
			// aapt resource value: 0x7f050018
			public const int lbGenreItem = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int lbYearItem = 2131034138;
			
			// aapt resource value: 0x7f050001
			public const int list = 2131034113;
			
			// aapt resource value: 0x7f050016
			public const int list_image = 2131034134;
			
			// aapt resource value: 0x7f050007
			public const int llButtons = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int llHeader = 2131034124;
			
			// aapt resource value: 0x7f050014
			public const int lvMovie = 2131034132;
			
			// aapt resource value: 0x7f05000f
			public const int lvTemp = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int tableLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int tableRow1 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int tableRow2 = 2131034117;
			
			// aapt resource value: 0x7f05001e
			public const int tableRow3 = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int tableRow4 = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int tableRow5 = 2131034146;
			
			// aapt resource value: 0x7f050024
			public const int tableRow6 = 2131034148;
			
			// aapt resource value: 0x7f050000
			public const int text = 2131034112;
			
			// aapt resource value: 0x7f050015
			public const int thumbnail = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int title = 2131034135;
			
			// aapt resource value: 0x7f05000e
			public const int tvDescriptionShowR = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int tvGenreDescription = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int tvGenreShow = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int tvIdShow = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int tvIdShowR = 2131034125;
			
			// aapt resource value: 0x7f050023
			public const int tvViewGenre = 2131034147;
			
			// aapt resource value: 0x7f050026
			public const int tvViewId = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int tvViewId1 = 2131034151;
			
			// aapt resource value: 0x7f05001c
			public const int tvViewTitle = 2131034140;
			
			// aapt resource value: 0x7f05001f
			public const int tvViewYear = 2131034143;
			
			// aapt resource value: 0x7f050006
			public const int txGenreDesciption = 2131034118;
			
			// aapt resource value: 0x7f05001d
			public const int txViewTitle = 2131034141;
			
			// aapt resource value: 0x7f050021
			public const int txViewYear = 2131034145;
			
			// aapt resource value: 0x7f05001b
			public const int year = 2131034139;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FindMovie = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Genre = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GenreListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MovieListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MyMovieAdd = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MyMovieEdit = 2130903046;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			private String()
			{
			}
		}
	}
}
